### ISSUE TITLE
app persistence problem

### ISSUE THREAD

**Issue by ninjatec** [wger-project/helm-charts#12]
When enabling persistence through the values the media and static volume mounts are not writable by the wger user.

**Comment by bbkz** [comment]
I have merged my older request, where i have worked on the persistent storage:

* `[wger-0.1.4-rc.1](https://github.com/wger-project/helm-charts/releases/tag/wger-0.1.4-rc.1)`

The thing is, django in a kubernetes environment requires at least two storages:

* media -> where all uploaded files go (exercise images)
* static -> where all css and js files will be

When using nginx or a other proxy these storages must be mounted in these images as well (ro). I have added this feature in:

* [wger-0.1.4-rc.2](https://github.com/wger-project/helm-charts/releases/tag/wger-0.1.4-rc.2)

Maybe you like to try one of these. Unfortunatly i have tested them only on `k3s` and not with the `minikube` setup...

**Comment by ninjatec** [comment]
I will look at these today and feedback.

**Comment by ninjatec** [comment]
rc.1 get this error when downloading static files, the directory listing shows the mount owned by root, the wger user has no access to write to the file-system. this is the same behaviour I saw in previous versions,

```
wger@wger-app-856d69cb98-qh24z:~/src$ df
Filesystem                        1K-blocks     Used Available Use% Mounted on
overlay                            48331140 26731256  19500768  58% /
tmpfs                                 65536        0     65536   0% /dev
/dev/mapper/ubuntu--vg-ubuntu--lv  48331140 26731256  19500768  58% /etc/hosts
shm                                   65536        0     65536   0% /dev/shm
/dev/sdj                             233767       14    216857   1% /home/wger/media
/dev/sdd                             233767       14    216857   1% /home/wger/static
tmpfs                               5569572       12   5569560   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                               3031296        0   3031296   0% /proc/acpi
tmpfs                               3031296        0   3031296   0% /proc/scsi
tmpfs                               3031296        0   3031296   0% /sys/firmware
wger@wger-app-856d69cb98-qh24z:~/src$ ls -ltr /home/wger
total 22
-rwxr-xr-x 1 root root 1729 Jul 11 16:28 entrypoint.sh
drwxr-xr-x 1 wger wger 4096 Jul 11 16:29 src
drwxr-xr-x 2 wger wger 4096 Jul 11 16:29 db
drwxr-xr-x 2 wger wger 4096 Jul 11 16:29 beat
drwxr-xr-x 3 root root 1024 Jul 25 15:00 static
drwxr-xr-x 3 root root 1024 Jul 25 15:00 media
wger@wger-app-856d69cb98-qh24z:~/src$ python3 manage.py collectstatic

You have requested to collect static files at the destination
location as specified in your settings:

    /home/wger/static

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Traceback (most recent call last):
  File "/home/wger/src/manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
    collected = self.collect()
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 135, in collect
    handler(path, prefixed_path, storage)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 378, in copy_file
    self.storage.save(prefixed_path, source_file)
  File "/usr/local/lib/python3.10/dist-packages/django/core/files/storage.py", line 56, in save
    name = self._save(name, content)
  File "/usr/local/lib/python3.10/dist-packages/django/core/files/storage.py", line 295, in _save
    os.makedirs(directory, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/wger/static/django_extensions'
wger@wger-app-856d69cb98-qh24z:~/src$
```

**Comment by bbkz** [comment]
i was thinking about how to write the things i have in my head ;-)

I am guessing you are using `minikube` and run it as your user with `containerd` as container runtime. I think then the user id of your user (running minikube) will be the user root (0) inside the container.

To fix this you can ether configure containerd with subuid/guid or change the folders permission to the id which is required inside the container.

**Comment by ninjatec** [comment]
I have a baremetal k8s lab, running ubuntu on vmware.

I was looking into using 
volumes.*.defaultMode or fsgroup to resolve this.

**Comment by bbkz** [comment]
Interesting... i didn't had such problem. I am using `cephfs.csi.ceph.com` for my storage volumes...

**Comment by rolandgeider** [comment]
Can we use volumes here? I always liked how they avoid all these user permissions/ID problems

**Comment by bbkz** [comment]
Just to share what i used for my PersistentVolume and PersistentVolumeClaim:

pv:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wger-media
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: default
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "XXXXXXXXXXXXXXXXXXXXXXXXXXXxx"
      "fsName": "cephfs"
      "staticVolume": "true"
      "rootPath": XXXXXXXXXXXXXXXXXXXXXXXXXX
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: wger-media
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: csi-cephfs-sc
```
pvc:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wger-media
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  # volumeName should be same as PV name
  volumeName: wger-media
  storageClassName: csi-cephfs-sc
```
