### ISSUE TITLE
FATAL error in postgres logs after helm deployment

### ISSUE THREAD

**Issue by amorabito** [wger-project/helm-charts#36]
Hello,

I installed the helm chart and was having issues logging in with a recently registered username/password.
I checked logs of postgres pod and found these logs, maybe it is related?

`FATAL:  role "postgres" does not exist`

I have attached values yaml used

[sample_values.txt](https://github.com/wger-project/helm-charts/files/13380064/sample_values.txt)

**Comment by bbkz** [comment]
Just, that i understand this right, you have:

* installed it and it is up and running
* you are able to login as admin
* the user which is not working was registered through the webinterface

**Comment by bbkz** [comment]
I also have constant

```bash
FATAL:  role "postgres" does not exist
```

but i am able to login with my account. I will have a look into the posgresql setup to fix that error.

**Comment by bbkz** [comment]
It is possible that setting the following in the `values.yml` could fix the FATAL error:

```yaml
postgres:
  # Note: keep these variables present as the chart uses them for the Deployment
  enabled: true
  settings:
    superuser: postgres
    superuserPassword: postgres
  userDatabase:
    name: wger
    user: wger
    password: wger
```

But this needs to be tested first.

**Comment by bbkz** [comment]
The following environment variables are required, when this change is made.

```yaml
app:
  environment:
    - name: DJANGO_DB_USER
      value: "wger"
    - name: DJANGO_DB_PASSWORD
      value: "wger"
```
