### ISSUE TITLE
Init container makes assumptions about the name of the host running PostgreSQL and gets stuck in the Init state.

### ISSUE THREAD

**Issue by dmbrownlee** [wger-project/helm-charts#58]
I'm using a pre-existing "wger" database that exists in the "cnpg" namespace (created with the CloudNativePG operator (https://cloudnative-pg.io/).  The hostname of the cluster service referencing the writable database is wger.cnpg.svc.cluster.local (still listening on port 5432).

I'm installing the helm chart with a values.yml which sets postgres.enable to false since I do not need it to create the database.  The wger-app pod gets stuck in the Init state because the nc command in the init-container is trying to connect to wger-postgres (templates/deployment.yaml is setting this to "{{.Release.Name}}-postgres" rather than using the DJANGO_DB_HOST environment variable (or a new variable to be added to the values.yaml file).

The simple workaround is editing the deployment and setting the correct hostname in the deployment manifest.  I'm thinking you might add a variable to values.yaml (app.django.dbhost?) and update the template/deployment.yaml to use that.  That said, I'm not a software developer so I don't know what the best fix would be.

**Comment by bbkz** [comment]
Hi, thank you for the report. I'll have a look into it.

**Comment by bbkz** [comment]
I am adding the following, what do you think?

* support existing database
  * credentials in the values.yaml
  * credentials in a existing secret

```yaml
app:
  django:
    # for existing databases use the following settings
    # you need to set `postgres.enabled: false` as well
    existingDatabase:
      enabled: false
      # set DJANGO_DB_ENGINE
      engine: null
      # set DJANGO_DB_HOST
      host: null
      # set DJANGO_DB_PORT
      port: null
      # set DJANGO_DB_DATABASE
      dbname: wger
      # set DJANGO_DB_USER
      dbuser: wger
      # set DJANGO_DB_PASSWORD
      dbpw: null
      # existing secret key containing database credentials
      existingSecret:
        # name of the secret
        name: null
        # overrides app.django.existingDatabase.dbname
        dbnameKey: null
        # overrides app.django.existingDatabase.dbuser
        dbuserKey: null
        # overrides app.django.existingDatabase.dbpw
        dbpwKey: null
```

**Comment by dmbrownlee** [comment]
That should work.  If values are set in both the values.yaml and an existing secret, which takes precedence?  Just curious, I can't think of a reason to assign values to both.

**Comment by bbkz** [comment]
When for example the `existingSecret.name` is set it will take that secret and look for the key `existingSecret.dbuserKey`, if the `existingSecret.dbuserKey` is not set it will look for `USERDB_USER`.

If no `existingSecret.name` is given it will take the values and create a new secret named `{{ .Release.Name}}-existing-database` with the settings.

So basically it `existingSecret.name` will take precedence.

I added a pre-release with the changes:

* https://github.com/wger-project/helm-charts/releases/tag/wger-0.2.4-rc.1

**Comment by dmbrownlee** [comment]
Installing from the wger-0.2.4-rc.1 tarball worked for me using the attributes under existingDatabase.  I'll reconfigure to use existingSecret when I get a chance, but I wanted to let you know the issue with the original issue with the init-container command is fixed.

**Comment by bbkz** [comment]
Nice, thank's for the feedback. I'll then close the issue when i make the proper release.

**Comment by dmbrownlee** [comment]
Oh, just to be clear, the original issue is not that there is no variable to set, but that the command in the init container doesn't use the existing variables.  This is the line I have to tweak:

**Comment by dmbrownlee** [comment]
I've done some more testing and it looks like there is still an issue when using existing secrets with the existing database.  I think the source of the unexpected behavior might be a tight coupling of the credentials with the database.

First, here is what worked with my initial testing:
```shell
/usr/local/bin/helm upgrade -i --reset-values --create-namespace --namespace wger wger 'wger/wger' --version=0.2.4-rc.1 --values wger.values
```
with the `wger.values` file containing:
```wger.values
app:
  global:
    replicas: 1
  persistence:
    enabled: true
  django:
    existingDatabase:
      enabled: true
      host: wger-rw.cnpg
      dbpw: wger
postgres:
  enabled: false
```

I confirmed that I can also install this without the wger.values file using:
```shell
/usr/local/bin/helm upgrade -i --reset-values --wait --create-namespace --namespace wger wger 'wger/wger' --version=0.2.4-rc.1   --set-string 'app.global.replicas=1'   --set app.persistence.enabled=true   --set app.django.existingDatabase.enabled=true   --set-string 'app.django.existingDatabase.host=wger-rw.cnpg'   --set-string 'app.django.existingDatabase.dbpw=wger'   --set postgres.enabled=false
```

Notice that in both the cases above, I do not set the name of the database and it defaults to "wger" as expected.  However, when I also try to use an existing secret without setting the database name in the secret, the database name no longer defaults to "wger" resulting a `CreateContainerConfigError` status for the wger-app pod.  That is to say, the following command fails to start the wger-app pod when the secret does not contain `USERDB_NAME`:

```shell
/usr/local/bin/helm upgrade -i --reset-values --wait --create-namespace --namespace wger wger 'wger/wger' --version=0.2.4-rc.1   --set-string 'app.global.replicas=1'   --set app.persistence.enabled=true   --set app.django.existingDatabase.enabled=true   --set-string 'app.django.existingDatabase.host=wger-rw.cnpg'   --set-string 'app.django.existingDatabase.existingSecret.name=wger-credentials'   --set-string 'app.django.existingDatabase.existingSecret.dbuserKey=username'   --set-string 'app.django.existingDatabase.existingSecret.dbpwKey=password'   --set postgres.enabled=false
```

Adding `--set-string 'app.django.existingDatabase.dbname=wger'` doesn't seem to help.  The workaround for this is to just include `USERDB_NAME` in the secret, but it seems like this is an unnecessary coupling of the credentials and the database.

This is still better than the original issue as it can be worked around in config files, but I'm wondering if it would be better to do something like:

```yaml
app:
  django:
    database:
      existingConfigj:
        name:
      # or
      engine: null
      host: null
      port: null
      dbname: wger
    credentials:
      existingSecret:
        name:
      # or
      username:
      password:
```

That is to say, keep the database name separate from the credentials (not that you should be reusing the same credentials for multiple uses 😉)

Either way, the release candidate works for me now that I know what to expect.
