### ISSUE TITLE
Missing static files on fresh install

### ISSUE THREAD

**Issue by maitredede** [wger-project/helm-charts#62]
Hello,

I have deployed a fresh install of wger with :
- chart version 0.2.4
- wget latest (at date of writing, may be 2.3)

In my values file, I have activated storage and nginx, and set my storageClass.

When it was all ready, I browsed to my url, but all static files went 404.

To fix it, I have executed in the pod : `./manager.py collect-static -v 2 --no-input` (the --clear returned an error due to volume permissions).

Since it is a time-consuming operation, I think it may not be added as an init container, but as a helm hook.

Or have I missed something ?

**Comment by maitredede** [comment]
Looks like it is due to the `--clear` argument on application startup, with permissions on `lost+found` directory.

A workaround fr this would be by using a single PVC, with `volumeMounts.subPath`. So the `lost+found` would be outside the mounted directory. But this would be hard to upgrade existing installations without reinstalling.

**Comment by bbkz** [comment]
Hi,

thank you for the report. Normally the static files are collected on every start of the container, see the `entrypoint.sh` of the containerfile:

* https://github.com/wger-project/wger/blob/b2d5b2a78413b218c95063156e774c024576f587/extras/docker/production/entrypoint.sh#L24

But this will not be called when `DJANGO_DEBUG` is set, so maybe you have defined that?

As you discovered as well starting the container can take quite some time, especially for the first time as it also has to setup the whole database.

As for the `lost+found`, then you must be using a ext4 filesystem? I am using a cephfs storage backend in my cluster, so my volumes don't have this issue... what storage solution do you use?

Yours,
bbk

**Comment by bbkz** [comment]
Oh.. i just checked what i do in the helm chart is:

```yaml
  - name: DJANGO_DEBUG
    {{- if .Values.app.nginx.enabled }}
    value: "False"
    {{- else }}
    value: "True"
    {{- end }}
```

So `app.nginx.enable` must be set in your `values.yaml` and don't override the `DJANGO_DEBUG`.

**Comment by maitredede** [comment]
I am using [https://longhorn.io/](longhorn) as volume provider. I have also installed [https://github.com/topolvm/topolvm](topolvm) and [https://rook.io/](rook) (for ceph orchestration, but I have not yet configured a ceph cluster).

The `lost+found` folder would be present on `ext4` volumes, that is the case for longhorn, topolvm, and ceph RBD. And on many clusters I think.

The value for `app.nginx.enabled` is `true` in my values file :

```yaml
app:
  timezone: "UTC"
  persistence:
    enabled: true
    storageClass: longhorn
    accessModes:
      - ReadWriteMany
    sizeMedia: 8Gi
    sizeStatic: 8Gi
    sizeCeleryBeat: 1Gi
  resources:
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 500m
  nginx:
    enabled: true
    image: nginx:stable
    imagePullPolicy: Always
  mail:
    enabled: false

ingress:
  enabled: true
  ingressClassName: nginx
  url: workout.local
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
postgres:
  enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  storage:
    requestedSize: 10Gi
    className: longhorn

redis:
  storage:
    requestedSize: 10Gi
    className: longhorn

celery:
  enabled: true
  flower:
    enabled: true
```
